import { SurfaceCard } from "@/components/branches/SurfaceCard"
import { EmptyNotice } from "@/components/composites/EmptyNotice"
import { EvidenceRow } from "@/components/composites/EvidenceRow"
import { LabelledProgressRow } from "@/components/composites/LabelledProgressRow"
import { Button } from "@/components/leaves/Button"
import { Heading } from "@/components/leaves/Heading"
import { Progress } from "@/components/leaves/Progress"
import { Text } from "@/components/leaves/Text"
/** Rendering state for the result journey. */
export type CourseMockInterviewResultState = "grading" | "gradingFailed" | "ready" | "failed"
/** One scored rubric phase. */
export type CourseMockInterviewScoreRow = { readonly id: string; readonly label: string; readonly score: number; readonly max: number }
/** One reviewed interview question. */
export type CourseMockInterviewQuestionReview = { readonly id: string; readonly title: string; readonly answer: string; readonly feedback: string; readonly scoreLabel: string }
/** Localized content and result data for the debrief. */
export type CourseMockInterviewResultData = { readonly resultState?: CourseMockInterviewResultState; readonly title: string; readonly description: string; readonly gradingLabel: string; readonly gradingFailedLabel: string; readonly gradingFailureDetail: string; readonly gradingAttemptLabel?: string; readonly retryingLabel: string; readonly failedLabel: string; readonly scoreLabel: string; readonly score?: number; readonly verdict?: string; readonly promptTitle?: string; readonly phaseTitle: string; readonly phases: ReadonlyArray<CourseMockInterviewScoreRow>; readonly strengthsTitle: string; readonly strengths: ReadonlyArray<string>; readonly gapsTitle: string; readonly gaps: ReadonlyArray<string>; readonly reviewsTitle: string; readonly reviews: ReadonlyArray<CourseMockInterviewQuestionReview>; readonly retryLabel: string; readonly abandonLabel: string; readonly newSessionLabel: string; readonly openTranscriptLabel: string; readonly openHistoryLabel: string; readonly returnToCourseLabel: string; readonly actionsTitle?: string; readonly sessionSummaryTitle: string; readonly sessionSummaryPromptLabel: string; readonly sessionSummaryQuestionLabel: string; readonly recommendationTitle: string; readonly recommendation?: string; readonly retrying: boolean; readonly canRetryGrading: boolean }
/** User actions emitted by the debrief. */
export type CourseMockInterviewResultActions = { readonly retry?: () => void; readonly abandon?: () => void; readonly newSession?: () => void; readonly openTranscript?: () => void; readonly openHistory?: () => void; readonly returnToCourse?: () => void }
/** State, data and actions passed to the presentational result block. */
export type CourseMockInterviewResultBlockProps = { readonly state: CourseMockInterviewResultState; readonly props: CourseMockInterviewResultData; readonly on?: CourseMockInterviewResultActions }
/** Presentational debrief for a graded interview attempt. */
export const CourseMockInterviewResultBlockBase = (props: CourseMockInterviewResultBlockProps) => {
    const state = props.props.resultState ?? props.state
    const loading = state === "grading"
    const actions = state === "gradingFailed" ? <><>{props.props.canRetryGrading ? <Button props={{ label: props.props.retrying ? props.props.retryingLabel : props.props.retryLabel, variant: "primary", isPending: props.props.retrying }} on={{ press: props.on?.retry }} /> : null}</><Button props={{ label: props.props.abandonLabel, variant: "outline", disabled: props.props.retrying }} on={{ press: props.on?.abandon }} /></> : <><Button props={{ label: props.props.newSessionLabel, variant: "primary" }} on={{ press: props.on?.newSession }} /><Button props={{ label: props.props.openTranscriptLabel, variant: "outline" }} on={{ press: props.on?.openTranscript }} /><Button props={{ label: props.props.openHistoryLabel, variant: "outline" }} on={{ press: props.on?.openHistory }} /><Button props={{ label: props.props.returnToCourseLabel, variant: "outline" }} on={{ press: props.on?.returnToCourse }} /></>
    return <main><header><Heading props={{ content: props.props.title, level: 1 }} isLoading={loading} /><Text props={{ content: props.props.description, size: "sm", tone: "muted" }} isLoading={loading} /></header>{state === "failed" ? <EmptyNotice props={{ message: props.props.failedLabel, actionLabel: props.props.retryLabel }} on={{ act: props.on?.retry }} /> : null}{state === "grading" ? <><EmptyNotice props={{ message: props.props.gradingLabel }} /><Progress props={{ label: props.props.gradingLabel }} isLoading /></> : null}{state === "gradingFailed" ? <SurfaceCard props={{ label: props.props.gradingFailedLabel }}><Text props={{ content: props.props.gradingFailureDetail, size: "sm", tone: "muted" }} />{props.props.gradingAttemptLabel === undefined ? null : <Text props={{ content: props.props.gradingAttemptLabel, size: "xs", tone: "muted" }} />}{actions}</SurfaceCard> : null}{state === "ready" ? <><SurfaceCard props={{ label: props.props.scoreLabel }}><Text props={{ content: `${props.props.score ?? 0}/100`, size: "sm" }} /><Heading props={{ content: props.props.verdict, level: 2 }} /><Text props={{ content: props.props.promptTitle, size: "sm", tone: "muted" }} /></SurfaceCard><SurfaceCard props={{ label: props.props.phaseTitle }}>{props.props.phases.map((item) => <LabelledProgressRow key={item.id} props={{ id: item.id, title: item.label, percent: item.max === 0 ? 0 : (item.score / item.max) * 100, percentText: `${item.score}/${item.max}` }} />)}</SurfaceCard><SurfaceCard props={{ label: props.props.strengthsTitle }}>{props.props.strengths.map((item) => <Text key={item} props={{ content: item, size: "sm" }} />)}</SurfaceCard><SurfaceCard props={{ label: props.props.gapsTitle }}>{props.props.gaps.map((item) => <Text key={item} props={{ content: item, size: "sm" }} />)}</SurfaceCard>{props.props.reviews.length === 0 ? null : <SurfaceCard props={{ label: props.props.reviewsTitle }}>{props.props.reviews.map((item) => <EvidenceRow key={item.id} props={{ title: `${item.title}: ${item.answer}`, subtitle: item.feedback, fact: item.scoreLabel }} />)}</SurfaceCard>}{props.props.recommendation === undefined ? null : <SurfaceCard props={{ label: props.props.recommendationTitle }}><Text props={{ content: props.props.recommendation, size: "sm" }} /></SurfaceCard>}<SurfaceCard props={{ label: props.props.sessionSummaryTitle }}><Text props={{ content: `${props.props.sessionSummaryPromptLabel}: ${props.props.promptTitle ?? "—"}`, size: "sm" }} /><Text props={{ content: `${props.props.sessionSummaryQuestionLabel}: ${props.props.reviews.length}`, size: "sm", tone: "muted" }} /></SurfaceCard><SurfaceCard props={{ label: props.props.actionsTitle ?? props.props.newSessionLabel }}>{actions}</SurfaceCard></> : null}</main>
}
