import { fireEvent, render, screen } from "@testing-library/react"
import { describe, expect, it, vi } from "vitest"
import { CourseLearnChallengeBlockBase, type CourseLearnChallengePageProps } from "@/components/blocks/learn/CourseLearnChallengeBlock/component"

const baseProps: CourseLearnChallengePageProps["props"] = {
    title: "Repository challenge", courseTitle: "Fullstack Mastery", moduleTitle: "Foundations", contentTitle: "Dependency injection", description: "Submit the authored deliverable.", difficultyLabel: "Hard", statusLabel: "Not submitted", hint: "Keep the public API stable.",
    prerequisites: [{ id: "prerequisite-1", body: "Know dependency inversion." }], requirements: [{ id: "requirement-1", title: "Stable contract", body: "Keep the public API stable.", score: 6 }], steps: [{ id: "step-1", title: "Extract the port", body: "Move the dependency behind an interface." }], outputs: [{ id: "output-1", body: "A public repository with smoke-test evidence." }], maximumScore: 10, deliverables: [{ id: "submission-1", title: "API repository", description: "Provide the repository URL.", score: 10, url: "https://example.test/repository" }], expandedRequirementIds: ["submission-1"], expandedStepIds: ["step-1"], isCourseMapOpen: false, isConfirmOpen: false, allDraftsComplete: true, draftStatus: "Draft saved", courseMap: { state: "ready", props: { labels: { progress: "Course progress", searchPlaceholder: "Search contents", searchLabel: "Search this course", searchClearLabel: "Clear search", failed: "Course outline failed" }, completionPercent: 50, progressFact: "1/2", modules: [] } },
    labels: { backToLesson: "Back to lesson", openCourseMap: "Course contents", brief: "Challenge brief", deliverables: "Submit your work", prerequisites: "Before you start", requirements: "Scored requirements", steps: "Suggested approach", expectedOutputs: "Expected outputs", hintLabel: "Hint", evidenceLabel: "Repository evidence", gradingModel: "Grading model", changeModel: "Choose grading model", language: "Language", askAi: "Ask AI", saveAndExit: "Save and exit", repositoryPlaceholder: "https://github.com/…", saved: "Saved locally", saveDraft: "Save draft", retrySave: "Retry save", submitAttempt: "Submit complete attempt", confirmTitle: "Submit this attempt?", confirmDescription: "The submitted revision cannot be edited.", confirmSubmit: "Submit and evaluate", cancel: "Keep editing", breadcrumb: "Course challenge path", retry: "Retry", result: "Open graded result", points: (score) => `${score} points`, reviewAttempt: "Review attempt", reviewTitle: "Review attempt", reviewDescription: "Check your evidence.", returnToEdit: "Keep editing", scoreValue: (score, maximum) => `${score} / ${maximum} points` },
}

describe("CourseLearnChallengeBlockBase", () => {
    it("renders the challenge document, brief and actions", () => { render(<CourseLearnChallengeBlockBase blockState="ready" props={baseProps} />); expect(screen.getByRole("heading", { name: "Repository challenge", level: 1 })).toBeInTheDocument(); expect(screen.getByRole("heading", { name: "Scored requirements", level: 2 })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Course contents" })).toBeInTheDocument() })
    it("renders authored guidance", () => { render(<CourseLearnChallengeBlockBase blockState="ready" props={baseProps} />); expect(screen.getByText("Know dependency inversion.")).toBeInTheDocument(); expect(screen.getByText("Move the dependency behind an interface.")).toBeInTheDocument(); expect(screen.getByText("A public repository with smoke-test evidence.")).toBeInTheDocument() })
    it("routes requirement disclosure", () => { const toggle = vi.fn(); render(<CourseLearnChallengeBlockBase blockState="ready" props={{ ...baseProps, requirements: [...(baseProps.requirements ?? []), { id: "requirement-2", title: "Second contract", body: "Keep the second boundary stable.", score: 4 }], expandedRequirementIds: [] }} on={{ toggleRequirement: toggle }} />); fireEvent(screen.getByText("Second contract").closest("details") as HTMLElement, new Event("toggle")); expect(toggle).toHaveBeenCalledWith("requirement-2", false) })
    it("routes step disclosure", () => { const toggle = vi.fn(); render(<CourseLearnChallengeBlockBase blockState="ready" props={{ ...baseProps, steps: [...(baseProps.steps ?? []), { id: "step-2", title: "Verify the boundary", body: "Confirm the boundary." }], expandedStepIds: [] }} on={{ toggleStep: toggle }} />); fireEvent(screen.getByText("Verify the boundary").closest("details") as HTMLElement, new Event("toggle")); expect(toggle).toHaveBeenCalledWith("step-2", false) })
    it("shows two pending evidence rows and disables submit", () => { render(<CourseLearnChallengeBlockBase blockState="pending" props={baseProps} />); expect(screen.getAllByRole("textbox")).toHaveLength(2); expect(screen.getByRole("button", { name: "Submit complete attempt" })).toBeDisabled() })
    it("supports model selection and immutable review", () => { const open = vi.fn(); const { rerender } = render(<CourseLearnChallengeBlockBase blockState="ready" props={baseProps} on={{ openModelDrawer: open }} />); fireEvent.click(screen.getByRole("button", { name: "Choose grading model" })); expect(open).toHaveBeenCalledTimes(1); rerender(<CourseLearnChallengeBlockBase blockState="ready" props={{ ...baseProps, isReviewing: true }} />); expect(screen.queryByLabelText("Repository evidence")).not.toBeInTheDocument(); expect(screen.getByRole("heading", { name: "Review attempt" })).toBeInTheDocument() })
    it("edits evidence and starts review", () => { const change = vi.fn(); const review = vi.fn(); render(<CourseLearnChallengeBlockBase blockState="ready" props={baseProps} on={{ changeUrl: change, reviewAttempt: review }} />); fireEvent.change(screen.getByLabelText("Repository evidence"), { target: { value: "https://example.test/next" } }); fireEvent.click(screen.getByRole("button", { name: "Review attempt" })); expect(change).toHaveBeenCalledWith("submission-1", "https://example.test/next"); expect(review).toHaveBeenCalledTimes(1) })
    it("locks controls while submitting", () => { render(<CourseLearnChallengeBlockBase blockState="submitting" props={baseProps} />); expect(screen.getByLabelText("Repository evidence")).toBeDisabled(); expect(screen.getByRole("button", { name: "Submit complete attempt" })).toBeDisabled() })
    it("keeps failed evidence and retries", () => { const retry = vi.fn(); render(<CourseLearnChallengeBlockBase blockState="failed" props={{ ...baseProps, failedSubmissionId: "submission-1", notice: "Submission refused" }} on={{ retry }} />); expect(screen.getByLabelText("Repository evidence")).toHaveAttribute("aria-invalid", "true"); fireEvent.click(screen.getByRole("button", { name: "Retry save" })); expect(retry).toHaveBeenCalledTimes(1) })
    it("opens the graded result after passing", () => { const open = vi.fn(); render(<CourseLearnChallengeBlockBase blockState="passed" props={{ ...baseProps, statusLabel: "Passed" }} on={{ openResult: open }} />); expect(screen.queryByLabelText("Repository evidence")).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Open graded result" })); expect(open).toHaveBeenCalledWith("submission-1") })
    it("routes the course map control", () => { const open = vi.fn(); render(<CourseLearnChallengeBlockBase blockState="ready" props={baseProps} on={{ openCourseMap: open }} />); fireEvent.click(screen.getByRole("button", { name: "Course contents" })); expect(open).toHaveBeenCalledTimes(1) })
})
