import { SurfaceCard } from "@/components/branches/SurfaceCard"
import { EvidenceRow } from "@/components/composites/EvidenceRow"
import { Button } from "@/components/leaves/Button"
import { Heading } from "@/components/leaves/Heading"
import { Progress } from "@/components/leaves/Progress"
import { Text } from "@/components/leaves/Text"
import type { ProfileCapstone } from "@/modules/api/graphql/queries/types/profile-evidence"
/** Pure roadmap data and route action. */
export type ProfileProjectRoadmapProps = { readonly state: "pending" | "ready" | "error"; readonly project?: ProfileCapstone; readonly onBack: () => void }
/** Draw capstone summary and milestone roadmap. */
export const ProfileProjectRoadmapBase = (props: ProfileProjectRoadmapProps) => { const loading = props.state === "pending"; const project = props.project; const value = Math.round((project?.completedTasks ?? 0) / Math.max(1, project?.totalTasks ?? 0) * 100); const milestones = project?.milestones ?? []; return <div><Button props={{ label: "← Projects", variant: "ghost", size: "sm" }} on={{ press: props.onBack }} /><Heading props={{ content: props.state === "error" ? "Capstone couldn't be loaded" : project?.courseTitle ?? (loading ? undefined : "Capstone not found"), level: 2 }} isLoading={loading} /><Text props={{ content: project ? `${project.completedMilestones}/${project.totalMilestones} milestones · ${project.completedTasks}/${project.totalTasks} tasks · Verified by StarCi` : props.state === "ready" ? "This capstone is not public." : undefined, size: "sm", tone: "muted" }} isLoading={loading} />{(project || loading) && <Progress props={{ value, label: "Capstone completion" }} isLoading={loading} />}<SurfaceCard props={{ label: "Roadmap" }}>{milestones.length ? milestones.map((milestone) => <EvidenceRow key={milestone.milestoneGlobalId} props={{ title: milestone.title, subtitle: `${milestone.passedTasks}/${milestone.totalTasks} tasks passed`, fact: milestone.passedTasks === milestone.totalTasks && milestone.totalTasks > 0 ? "Passed" : `${Math.round(milestone.passedTasks / Math.max(1, milestone.totalTasks) * 100)}%`, factTone: milestone.passedTasks === milestone.totalTasks && milestone.totalTasks > 0 ? "success" : "accent" }} isLoading={loading} />) : <EvidenceRow props={{ title: props.state === "error" ? "Roadmap couldn't be loaded." : "No public roadmap was found." }} />}</SurfaceCard></div> }
