import { SurfaceListCard } from "@/components/branches/SurfaceListCard"
import { EmptyNotice } from "@/components/composites/EmptyNotice"
import { EvidenceRow } from "@/components/composites/EvidenceRow"
import { Button } from "@/components/leaves/Button"
import { Heading } from "@/components/leaves/Heading"
import { Progress } from "@/components/leaves/Progress"
import { Text } from "@/components/leaves/Text"
import type { ProfileCapstone } from "@/modules/api/graphql/queries/types/profile-evidence"
/** Pure roadmap data and route action. */
export type ProfileProjectRoadmapProps = { readonly state: "pending" | "ready" | "error"; readonly project?: ProfileCapstone; readonly onBack: () => void; readonly onRetry?: () => void }
/** Draw capstone summary and milestone roadmap. */
export const ProfileProjectRoadmapBase = (props: ProfileProjectRoadmapProps) => { const loading = props.state === "pending"; const project = props.project; const value = Math.round((project?.completedTasks ?? 0) / Math.max(1, project?.totalTasks ?? 0) * 100); const milestones = project?.milestones ?? []; const resting = Array.from({ length: 3 }, (_, index) => ({ milestoneGlobalId: `resting-${index}`, title: "", passedTasks: 0, totalTasks: 0 })); const rows = loading ? resting : milestones; return <div><Button props={{ label: "← Projects", variant: "ghost", size: "sm" }} on={{ press: props.onBack }} /><Heading props={{ content: props.state === "error" ? "Capstone couldn't be loaded" : project?.courseTitle ?? (loading ? undefined : "Capstone not found"), level: 2 }} isLoading={loading} />{props.state === "error" ? <Button props={{ label: "Try again", variant: "secondary", size: "sm", icon: "retry" }} on={{ press: props.onRetry }} /> : null}<Text props={{ content: project ? `${project.completedMilestones}/${project.totalMilestones} milestones · ${project.completedTasks}/${project.totalTasks} tasks · Verified by StarCi` : props.state === "ready" ? "This capstone is not public." : undefined, size: "sm", tone: "muted" }} isLoading={loading} />{(project || loading) && <Progress props={{ value, label: "Capstone completion" }} isLoading={loading} />}<SurfaceListCard props={{ label: "Roadmap" }} isLoading={loading}>{!loading && rows.length === 0 ? <EmptyNotice props={{ icon: props.state === "error" ? "retry" : "course", message: props.state === "error" ? "Roadmap couldn't be loaded." : "No public roadmap was found.", actionLabel: props.state === "error" ? "Try again" : undefined, actionIcon: "retry" }} on={{ act: props.onRetry }} /> : rows.map((milestone) => <EvidenceRow key={milestone.milestoneGlobalId} props={{ title: milestone.title, subtitle: `${milestone.passedTasks}/${milestone.totalTasks} tasks passed`, fact: loading ? undefined : milestone.passedTasks === milestone.totalTasks && milestone.totalTasks > 0 ? "Passed" : `${Math.round(milestone.passedTasks / Math.max(1, milestone.totalTasks) * 100)}%`, factTone: milestone.passedTasks === milestone.totalTasks && milestone.totalTasks > 0 ? "success" : "accent" }} isLoading={loading} />)}</SurfaceListCard></div> }
