import { SurfaceListCard } from "@starci/grammar/common"
import { Icon } from "@starci/grammar/common"
import { iconSourceFor } from "@/components/leaves/Icon"
import { EmptyNotice } from "@starci/grammar/common"
import { EvidenceRow } from "@/components/composites/EvidenceRow"
import { Button } from "@starci/grammar/common"
import { Heading } from "@starci/grammar/common"
import { Progress } from "@starci/grammar/common"
import { Text } from "@starci/grammar/common"
import type { ProfileCapstone } from "@/modules/api/graphql/queries/types/profile-evidence"
/** Pure roadmap data and route action. */
export type ProfileProjectRoadmapProps = { readonly state: "pending" | "ready" | "error"; readonly project?: ProfileCapstone; readonly onBack: () => void; readonly onRetry?: () => void }
/** Draw capstone summary and milestone roadmap. */
export const ProfileProjectRoadmapBase = (props: ProfileProjectRoadmapProps) => { const loading = props.state === "pending"; const project = props.project; const milestones = project?.milestones ?? []; const resting = Array.from({ length: 3 }, (_, index) => ({ milestoneGlobalId: `resting-${index}`, title: "", passedTasks: 0, totalTasks: 0 })); const rows = loading ? resting : milestones; return <div><Button variant="ghost" size="sm" onPress={props.onBack}>{"← Projects"}</Button><Heading level={2} isSkeleton={loading}>{props.state === "error" ? "Capstone couldn't be loaded" : project?.courseTitle ?? (loading ? undefined : "Capstone not found")}</Heading>{props.state === "error" ? <Button variant="secondary" size="sm" onPress={props.onRetry}>{"Try again"}</Button> : null}<Text size={"sm"} tone={"muted"} isSkeleton={loading}>{project ? `${project.completedMilestones}/${project.totalMilestones} milestones · ${project.completedTasks}/${project.totalTasks} tasks · Verified by StarCi` : props.state === "ready" ? "This capstone is not public." : undefined}</Text>{(project || loading) && <Progress label={"Capstone completion"} isSkeleton={loading} />}<SurfaceListCard label={"Roadmap"} isLoading={loading}>{!loading && rows.length === 0 ? <EmptyNotice message={props.state === "error" ? "Roadmap couldn't be loaded." : "No public roadmap was found."} actionLabel={props.state === "error" ? "Try again" : undefined} iconSource={iconSourceFor(props.state === "error" ? "retry" : "course", "leading")} actionStartContent={<Icon source={iconSourceFor("retry", "chip")} role="chip" />} onAction={({ act: props.onRetry })?.act} /> : rows.map((milestone) => <EvidenceRow key={milestone.milestoneGlobalId} props={{ title: milestone.title, subtitle: `${milestone.passedTasks}/${milestone.totalTasks} tasks passed`, fact: loading ? undefined : milestone.passedTasks === milestone.totalTasks && milestone.totalTasks > 0 ? "Passed" : `${Math.round(milestone.passedTasks / Math.max(1, milestone.totalTasks) * 100)}%`, factTone: milestone.passedTasks === milestone.totalTasks && milestone.totalTasks > 0 ? "success" : "accent" }} isLoading={loading} />)}</SurfaceListCard></div> }
