import { SurfaceCard } from "@/components/branches/SurfaceCard"
import { Tree } from "@/components/branches/Tree"
import { EvidenceRow } from "@/components/composites/EvidenceRow"
import { ProfileMetric } from "@/components/composites/ProfileMetric"
import { ProfileSegment } from "@/components/composites/ProfileSegment"
import { Badge } from "@/components/leaves/Badge"
import { Button } from "@/components/leaves/Button"
import { SearchBox } from "@/components/leaves/SearchBox"
import { Text } from "@/components/leaves/Text"
import { defineCompositeComponent, defineContractComponent, defineContractProjection, defineLeafComponent } from "@/components/contracts/props"
import type { ProfileBreakdown, ProfileCodingHistory } from "@/modules/api/graphql/queries/types/profile-evidence"
/** Resolved coding evidence and local history actions owned by the block. */
export type ProfileSkillsBlockProps = { readonly state: "pending" | "ready" | "error"; readonly props: { readonly metrics: ReadonlyArray<{ readonly id: string; readonly value: string; readonly label: string }>; readonly byDifficulty: ReadonlyArray<ProfileBreakdown>; readonly byDomain: ReadonlyArray<ProfileBreakdown>; readonly byLanguage: ReadonlyArray<ProfileBreakdown>; readonly history: ReadonlyArray<ProfileCodingHistory>; readonly filterLabel: string }; readonly on?: { readonly search?: (query: string) => void; readonly filter?: () => void; readonly select?: (slug: string) => void } }
type BreakdownProps = { readonly label: string; readonly items: ReadonlyArray<ProfileBreakdown>; readonly chips?: boolean; readonly loading: boolean }
const ProfileMetrics = (input: ProfileSkillsBlockProps) => { const metrics = input.state === "pending" ? Array.from({ length: 4 }, (_, index) => ({ id: String(index), value: "", label: "" })) : input.props.metrics; return <SurfaceCard props={{ label: "Coding metrics" }} contract="profile-metric-ribbon" render={defineContractComponent("profile-metric-ribbon", { metric: metrics.map((metric) => defineCompositeComponent("profile-metric", {}, () => <ProfileMetric props={metric} isLoading={input.state === "pending"} />)) })} /> }
const Breakdown = ({ label, items, chips, loading }: BreakdownProps) => <Tree contract="profile-breakdown" render={defineContractComponent("profile-breakdown", { label: defineLeafComponent("text", { size: "sm", weight: "semibold" }, () => <Text props={{ content: label, size: "sm", weight: "semibold" }} isLoading={loading} />), visual: chips ? defineContractComponent("profile-topic-chip-run", { topic: (loading ? Array.from({ length: 4 }, (_, index) => ({ key: String(index), solved: 0 })) : items).map((item) => defineLeafComponent("badge", {}, () => <Badge props={{ content: loading ? "" : `${item.key} ${item.solved}`, tone: "neutral" }} isLoading={loading} />)) }) : defineContractComponent("profile-segment-run", { segment: (loading ? Array.from({ length: 3 }, (_, index) => ({ key: String(index), solved: 0 })) : items).map((item) => defineCompositeComponent("profile-segment", {}, () => <ProfileSegment props={{ label: loading ? "" : `${item.key} ${item.solved}` }} isLoading={loading} />)) }) })} />
const ProfileStats = (input: ProfileSkillsBlockProps) => <SurfaceCard props={{ label: "Stats" }} contract="profile-breakdown-stack" render={defineContractComponent("profile-breakdown-stack", { breakdown: [defineContractProjection("profile-breakdown", () => <Breakdown label="By difficulty" items={input.props.byDifficulty} loading={input.state === "pending"} />), defineContractProjection("profile-breakdown", () => <Breakdown label="By topic" items={input.props.byDomain} chips loading={input.state === "pending"} />), defineContractProjection("profile-breakdown", () => <Breakdown label="By language" items={input.props.byLanguage} loading={input.state === "pending"} />)] })} />
const ProfileHistory = (input: ProfileSkillsBlockProps) => { const rows = input.state === "pending" ? Array.from({ length: 3 }, (_, index): ProfileCodingHistory => ({ problemTitle: "", slug: `pending-${index}`, languages: [], firstSolvedAt: "" })) : input.props.history; return <SurfaceCard props={{ label: "Solve history", fact: input.state === "ready" ? `${rows.length} results` : undefined }} contract="profile-toolbar-over-list" render={defineContractComponent("profile-toolbar-over-list", { toolbar: defineContractComponent("profile-search-filter-row", { search: defineLeafComponent("search-box", {}, () => <SearchBox props={{ label: "Search solve history", placeholder: "Search solved problems", clearLabel: "Clear search" }} on={{ search: input.on?.search }} />), filter: defineLeafComponent("button", {}, () => <Button props={{ label: input.props.filterLabel, size: "sm" }} on={{ press: input.on?.filter }} />) }), list: defineContractComponent("profile-evidence-list", { evidence: rows.map((row) => defineCompositeComponent("evidence-row", {}, () => <EvidenceRow props={{ title: row.problemTitle, subtitle: [row.firstSolvedAt, row.domain, row.languages.join(" · ")].filter(Boolean).join(" · "), fact: row.difficulty ?? undefined, factTone: row.difficulty === "hard" ? "danger" : row.difficulty === "medium" ? "warning" : "success", isPressable: input.state === "ready" }} on={{ press: () => input.on?.select?.(row.slug) }} isLoading={input.state === "pending"} />)) }) })} /> }
/** Draw metrics, coding breakdowns, and searchable solve history. */
export const ProfileSkillsBase = (input: ProfileSkillsBlockProps) => <Tree contract="profile-main" render={defineContractComponent("profile-main", { section: [defineContractProjection("label-row-over-card", () => <ProfileMetrics {...input} />), defineContractProjection("label-row-over-card", () => <ProfileStats {...input} />), defineContractProjection("label-row-over-card", () => <ProfileHistory {...input} />)] })} />
/** Source-level ownership marker. */
export const meta = { world: "pure", domain: "profile" } as const
