type TestPageInput = { state: string; on: Record<string, (...args: ReadonlyArray<unknown>) => unknown> }
import { fireEvent, render, screen } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
const m = vi.hoisted(() => ({ course: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, session: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, result: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, sync: { isMutating: false, error: undefined as unknown, trigger: vi.fn().mockResolvedValue(true) }, rate: { isMutating: false, error: undefined as unknown, trigger: vi.fn().mockResolvedValue({ xpEarned: 2 }) }, complete: { isMutating: false, error: undefined as unknown, trigger: vi.fn().mockResolvedValue({}) }, push: vi.fn() }))
vi.mock("next-intl", () => ({ useLocale: () => "en" }))
vi.mock("@/i18n/navigation", () => ({ useRouter: () => ({ push: m.push, replace: m.push }) }))
vi.mock("@/hooks/swr/useQueryCourseSwr", () => ({ useQueryCourseSwr: () => m.course }))
vi.mock("@/hooks/swr/useQueryMyInProgressFlashcardSessionSwr", () => ({ useQueryMyInProgressFlashcardSessionSwr: () => m.session }))
vi.mock("@/hooks/swr/useQueryFlashcardSessionResultSwr", () => ({ useQueryFlashcardSessionResultSwr: () => m.result }))
vi.mock("@/hooks/swr/useMutateSyncFlashcardSessionSwr", () => ({ useMutateSyncFlashcardSessionSwr: () => m.sync, useMutateRateFlashcardSwr: () => m.rate }))
vi.mock("@/hooks/swr/useMutateCompleteFlashcardSessionSwr", () => ({ useMutateCompleteFlashcardSessionSwr: () => m.complete }))
vi.mock("./component", () => ({ CourseFlashcardSessionPageBase: ({ state, on }: TestPageInput) => <><output data-testid="state">{state}</output><button onClick={on.reveal}>reveal</button><button onClick={() => on.rate(2)}>rate</button><button onClick={on.retry}>retry</button><button onClick={on.leave}>leave</button></> }))
import { CourseFlashcardSessionPage } from "./index"
beforeEach(() => { vi.clearAllMocks(); m.course.data = { id: "c1" }; m.course.error = undefined; m.session.data = undefined; m.session.error = undefined; m.result.data = undefined; m.result.error = undefined; m.sync.error = undefined; m.rate.error = undefined; m.complete.error = undefined; m.sync.isMutating = false; m.rate.isMutating = false; m.complete.isMutating = false })
describe("CourseFlashcardSessionPage route", () => {
    it("reports pending, active, expired and failed states", () => { const view = render(<CourseFlashcardSessionPage displayId="course" sessionId="s1" mode="review" />); expect(screen.getByTestId("state")).toHaveTextContent("pending"); m.session.data = { cards: [{ cardId: "card", front: "Q", back: "A" }], currentIndex: 0, reviewedCount: 0, gradedIndexes: [], xpEarned: 0, kind: "deck" }; m.result.data = { status: "completed" }; view.rerender(<CourseFlashcardSessionPage displayId="course" sessionId="s1" mode="review" />); expect(screen.getByTestId("state")).toHaveTextContent("active"); m.session.data = null; m.result.data = { status: "in_progress" }; view.rerender(<CourseFlashcardSessionPage displayId="course" sessionId="s1" mode="review" />); expect(screen.getByTestId("state")).toHaveTextContent("expired"); m.session.error = new Error("offline"); view.rerender(<CourseFlashcardSessionPage displayId="course" sessionId="s1" mode="review" />); expect(screen.getByTestId("state")).toHaveTextContent("failed") })
    it("retries and leaves through the connected actions", () => { m.session.data = { cards: [{ cardId: "card", front: "Q", back: "A" }], currentIndex: 0, reviewedCount: 0, gradedIndexes: [], xpEarned: 0, kind: "deck" }; m.result.data = { status: "completed" }; render(<CourseFlashcardSessionPage displayId="course" sessionId="s1" mode="review" />); fireEvent.click(screen.getByText("retry")); fireEvent.click(screen.getByText("leave")); expect(m.course.mutate).toHaveBeenCalled(); expect(m.session.mutate).toHaveBeenCalled(); expect(m.result.mutate).toHaveBeenCalled(); expect(m.push).toHaveBeenCalledWith("/courses/course/learn/flashcards/review") })
})


