import { SurfaceCard } from "@/components/branches/SurfaceCard"
import { EmptyNotice } from "@/components/composites/EmptyNotice"
import { Breadcrumbs } from "@/components/leaves/Breadcrumbs"
import { Button } from "@/components/leaves/Button"
import { Heading } from "@/components/leaves/Heading"
import { Progress } from "@/components/leaves/Progress"
import { Text } from "@/components/leaves/Text"
import type { FlashcardSessionMode } from "@/modules/api/graphql/queries/query-my-in-progress-flashcard-session"
/** Finite transport and work states. */
export type CourseFlashcardSessionBlockState = "pending" | "active" | "syncing" | "completing" | "expired" | "failed"
/** Resolved cloze sentence and answer terms. */
export type CourseFlashcardClozeData = { readonly text: string; readonly blanks: ReadonlyArray<string>; readonly bank: ReadonlyArray<string>; readonly selected: ReadonlyArray<string>; readonly checked: boolean; readonly correctCount: number }
/** One position in the persisted session. */
export type CourseFlashcardQuestionItem = { readonly position: number; readonly state: "answered" | "current" | "future"; readonly selected: boolean; readonly disabled: boolean }
/** Display data for the session card. */
export type CourseFlashcardSessionBlockData = { readonly mode: FlashcardSessionMode; readonly title: string; readonly currentCard: number; readonly progressCard: number; readonly totalCards: number; readonly progressText: string; readonly readOnly: boolean; readonly questions: ReadonlyArray<CourseFlashcardQuestionItem>; readonly breadcrumbLabel: string; readonly modeBreadcrumbLabel: string; readonly taskBreadcrumbLabel: string; readonly courseTitle?: string; readonly deckTitle?: string; readonly level?: string | null; readonly prompt?: string; readonly answer?: string; readonly answerAvailable: boolean; readonly answerVisible: boolean; readonly cloze?: CourseFlashcardClozeData; readonly solutionVisible: boolean; readonly revealLabel: string; readonly promptLabel: string; readonly answerLabel: string; readonly answerUnavailableLabel: string; readonly answerUnavailableText: string; readonly sessionSummaryLabel: string; readonly modeLabel: string; readonly deckLabel: string; readonly levelLabel: string; readonly navigatorTitle: string; readonly navigatorDescription: string; readonly navigatorStateLabel: string; readonly answeredLabel: string; readonly selectedLabel: string; readonly currentLabel: string; readonly futureLabel: string; readonly readOnlyLabel: string; readonly readOnlyText: string; readonly previousLabel: string; readonly nextLabel: string; readonly continueHint: string; readonly clozeInstructionLabel: string; readonly wordBankLabel: string; readonly checkAnswerLabel: string; readonly showSolutionLabel: string; readonly resultLabel: string; readonly ratingLabel: string; readonly againLabel: string; readonly hardLabel: string; readonly goodLabel: string; readonly easyLabel: string; readonly syncingLabel: string; readonly completingLabel: string; readonly expiredText: string; readonly failedText: string; readonly retryLabel: string; readonly leaveLabel: string }
/** User actions supported by the live session. */
export type CourseFlashcardSessionBlockActions = { readonly reveal: () => void; readonly selectTerm: (term: string) => void; readonly checkQuiz: () => void; readonly showSolution: () => void; readonly rate: (grade: 0 | 1 | 2 | 3) => void; readonly selectQuestion: (position: number) => void; readonly previous: () => void; readonly next: () => void; readonly openCourse: () => void; readonly openMode: () => void; readonly retry: () => void; readonly leave: () => void }
/** Pure session renderer input. */
export type CourseFlashcardSessionProps = { readonly blockState: CourseFlashcardSessionBlockState; readonly data: CourseFlashcardSessionBlockData; readonly on: CourseFlashcardSessionBlockActions }
/** Legacy-named alias for page-level session props. */
/** Legacy-named alias for session presentation data. */
export type CourseFlashcardSessionPageData = CourseFlashcardSessionBlockData
/** Legacy-named alias for session actions. */
export type CourseFlashcardSessionPageActions = CourseFlashcardSessionBlockActions
/** Draw one focused review or quiz session with phase-legal controls. */
export const CourseFlashcardSessionBlockView = (props: CourseFlashcardSessionProps) => {
    const data = props.data
    const loading = props.blockState === "pending"
    if (props.blockState === "failed" || props.blockState === "expired") return <EmptyNotice props={{ message: props.blockState === "failed" ? data.failedText : data.expiredText, actionLabel: data.retryLabel }} on={{ act: props.on.retry }} />
    const cloze = data.mode === "quiz" ? data.cloze : undefined
    const answerAvailable = data.answerAvailable && typeof data.answer === "string" && data.answer.trim() !== ""
    const canRate = props.blockState === "active" && !data.readOnly && data.answerVisible && answerAvailable
    return <main aria-label={data.title}><header><Breadcrumbs props={{ label: data.breadcrumbLabel, showFullTrail: true, steps: [{ id: "course", label: data.courseTitle ?? "" }, { id: "mode", label: data.modeBreadcrumbLabel }, { id: "session", label: data.taskBreadcrumbLabel }] }} on={loading ? undefined : { course: props.on.openCourse, mode: props.on.openMode }} isLoading={loading} /><Heading props={{ content: data.title, level: 1 }} /><Button props={{ label: data.leaveLabel, variant: "outline", disabled: props.blockState === "syncing" || props.blockState === "completing" }} on={{ press: props.on.leave }} /></header><Progress props={{ label: data.progressText, value: data.totalCards === 0 ? 0 : Math.round(data.progressCard / data.totalCards * 100) }} isLoading={loading} /><section aria-label={data.promptLabel}><Text props={{ content: data.prompt, size: "md", weight: "medium" }} isLoading={loading} />{cloze === undefined ? null : <><Text props={{ content: data.clozeInstructionLabel, size: "xs", tone: "muted" }} /><Text props={{ content: cloze.text, size: "md" }} />{cloze.checked ? null : cloze.bank.filter((term) => !cloze.selected.includes(term)).map((term) => <Button key={term} props={{ label: term, size: "sm", variant: "outline" }} on={{ press: () => props.on.selectTerm(term) }} />)}{cloze.checked ? null : <Button props={{ label: data.checkAnswerLabel, variant: "primary", disabled: cloze.selected.length < cloze.blanks.length }} on={{ press: props.on.checkQuiz }} />}</>}{data.answerVisible ? <>{answerAvailable ? null : <Text props={{ content: data.answerUnavailableLabel, size: "sm", weight: "semibold" }} />}<Text props={{ content: answerAvailable ? data.answer : data.answerUnavailableText, size: "sm" }} /></> : <Button props={{ label: data.revealLabel, variant: "primary" }} on={{ press: props.on.reveal }} />}</section><aside aria-label={data.navigatorTitle}><Text props={{ content: data.navigatorDescription, size: "xs", tone: "muted" }} />{data.questions.map((question) => <Button key={question.position} props={{ label: String(question.position), size: "sm", variant: question.state === "current" ? "primary" : "outline", disabled: question.disabled }} on={{ press: () => props.on.selectQuestion(question.position) }} />)}</aside>{canRate ? <SurfaceCard props={{ label: data.ratingLabel }}>{([data.againLabel, data.hardLabel, data.goodLabel, data.easyLabel] as const).map((label, grade) => <Button key={label} props={{ label, variant: grade === 2 ? "primary" : "outline" }} on={{ press: () => props.on.rate(grade as 0 | 1 | 2 | 3) }} />)}</SurfaceCard> : null}</main>
}
