import type { ComponentType } from "react"
import { SurfaceAccordionCard } from "@starci/grammar/core"
import { SurfaceCard } from "@/components/branches/SurfaceCard"
import { SurfaceListCard } from "@/components/branches/SurfaceListCard"
import { Field } from "@/components/composites/Field"
import { Article, segmentArticleSurfaces } from "@/components/branches/Article"
import { Badge } from "@/components/leaves/Badge"
import { Button } from "@/components/leaves/Button"
import { DisclosureIndicator } from "@/components/leaves/DisclosureIndicator"
import { Heading } from "@/components/leaves/Heading"
import { Link } from "@/components/leaves/Link"
import { Text } from "@/components/leaves/Text"

/** One scored requirement authored for a personal-project task. */
export type PersonalProjectCriterion = { readonly id: string; readonly text: string; readonly score: number }
/** The settled loading, interaction and recovery conditions of the task page. */
export type PersonalProjectTaskState = "pending" | "ready" | "task-error" | "ancillary-unavailable" | "invalid-repository" | "submitting" | "submission-error" | "latest-result" | "forbidden"
/** Localized words and fact formatters owned by the connected task page. */
export type PersonalProjectTaskLabels = { readonly back: string; readonly guidance: string; readonly criteria: string; readonly showCriteria: string; readonly hideCriteria: string; readonly implementation: string; readonly points: (score: number) => string; readonly submission: string; readonly repository: string; readonly repositoryDescription: string; readonly repositoryPlaceholder: string; readonly settings: string; readonly language: string; readonly model: string; readonly branch: string; readonly branchPlaceholder: string; readonly token: string; readonly tokenPlaceholder: string; readonly tokenStored: (last4: string) => string; readonly settingsSaved: string; readonly evaluate: string; readonly feedback: string; readonly history: string; readonly latest: string; readonly passed: string; readonly needsWork: string; readonly saveSettings: string; readonly retry: string; readonly lockedTitle: string }
/** Complete authored task, submission and grading-settings props for the task renderer. */
export type PersonalProjectTaskProps = { readonly state: PersonalProjectTaskState; readonly props: { readonly title: string; readonly description: string; readonly difficulty?: string; readonly maxScore: number; readonly brief?: string; readonly hint?: string; readonly criteria: ReadonlyArray<PersonalProjectCriterion>; readonly expandedBriefSectionIds: ReadonlyArray<string>; readonly implementation?: string; readonly repositoryUrl?: string; readonly repositoryDraft?: string; readonly repositoryState: "ready" | "saving" | "invalid" | "failed"; readonly latestAttempt?: { readonly score: number; readonly passed: boolean }; readonly notice?: string; readonly labels: PersonalProjectTaskLabels }; readonly on?: { readonly back?: () => void; readonly toggleBriefSection?: (id: string, isOpen: boolean) => void; readonly changeRepository?: (value: string) => void; readonly openSettings?: () => void; readonly closeSettings?: () => void; readonly submit?: () => void; readonly retry?: () => void; readonly openFeedback?: () => void; readonly openHistory?: () => void }; readonly settingsOverlay?: ComponentType<{ readonly courseId: string; readonly taskId: string; readonly isOpen: boolean; readonly onDismiss: () => void }>; readonly settingsOverlayProps?: { readonly courseId: string; readonly taskId: string; readonly isOpen: boolean; readonly onDismiss: () => void } }

/** Draw the task brief, submission controls and grading actions. */
export const PersonalProjectTaskBase = (props: PersonalProjectTaskProps) => {
    const isLoading = props.state === "pending"
    const disabled = isLoading || props.state === "submitting" || props.state === "forbidden" || props.state === "task-error" || props.state === "ancillary-unavailable"
    const repositoryInvalid = props.props.repositoryState === "invalid"
    const recovery = props.state === "ancillary-unavailable" || props.state === "submission-error"
    const sourceSections = segmentArticleSurfaces(props.props.brief)
    const sections = sourceSections.length > 0 ? sourceSections : [{ id: "section-0", kind: "body" as const, body: props.props.brief ?? "", items: [] }]
    const brief = sections.map((section, index) => {
        if (section.kind === "peer-list") return <SurfaceListCard key={section.id} props={{ label: section.label ?? props.props.labels.guidance, isLabelHidden: section.label === undefined }} isLoading={isLoading}>{section.items.map((item) => <Article key={item.id} props={{ body: item.body }} isLoading={isLoading} />)}</SurfaceListCard>
        if (section.kind === "accordion") return <div key={section.id}><Heading props={{ content: section.label ?? props.props.labels.guidance, level: 3 }} /><SurfaceAccordionCard depth="top" items={section.items.map((item) => ({ id: item.id, isOpen: props.props.expandedBriefSectionIds.includes(item.id), summaryRender: <><Text props={{ content: item.title, weight: "semibold" }} isLoading={isLoading} /><DisclosureIndicator props={{ isOpen: props.props.expandedBriefSectionIds.includes(item.id) }} /></>, bodyRender: <Article props={{ body: item.body }} isLoading={isLoading} />}))} renderSummary={(summary) => <>{summary}</>} renderBody={(body) => <>{body}</>} onItemOpenChange={(id, open) => props.on?.toggleBriefSection?.(id, open)} /></div>
        return <SurfaceCard key={section.id} props={section.label === undefined ? undefined : { label: section.label }} isLoading={isLoading}><Article props={{ body: section.body }} isLoading={isLoading} />{index === 0 && props.props.hint !== undefined ? <Text props={{ content: props.props.hint, size: "sm", tone: "muted", icon: "review" }} /> : null}</SurfaceCard>
    })
    const implementation = props.props.implementation === undefined ? null : <SurfaceCard props={{ label: props.props.labels.implementation }}><Article props={{ body: props.props.implementation }} /></SurfaceCard>
    const criteria = props.props.criteria.length === 0 && !isLoading ? null : <SurfaceListCard props={{ label: props.props.labels.criteria }} isLoading={isLoading}>{props.props.criteria.map((criterion) => <div key={criterion.id}><Text props={{ content: criterion.text, size: "sm" }} isLoading={isLoading} /><Badge props={{ content: props.props.labels.points(criterion.score) }} isLoading={isLoading} /></div>)}</SurfaceListCard>
    const status = <Text props={{ content: props.props.notice, size: "sm", tone: "muted", live: "assertive" }} />
    const briefContent = props.state === "forbidden" ? <SurfaceCard props={{ label: props.props.labels.lockedTitle }}>{status}<Link props={{ label: props.props.labels.back, icon: "back" }} on={{ press: props.on?.back }} /></SurfaceCard> : props.state === "task-error" ? <SurfaceCard>{status}<Button props={{ label: props.props.labels.retry, variant: "primary" }} on={{ press: props.on?.retry }} /></SurfaceCard> : <>{brief}{implementation}{criteria}</>
    const submission = <SurfaceCard props={{ label: props.props.labels.submission }}><Field props={{ id: "personal-project-repository", name: "personal-project-repository", label: props.props.labels.repository, description: props.props.labels.repositoryDescription, placeholder: props.props.repositoryUrl ?? props.props.labels.repositoryPlaceholder, disabled, isInvalid: repositoryInvalid, hint: repositoryInvalid ? props.props.notice : props.props.repositoryUrl }} on={{ change: props.on?.changeRepository }} isLoading={isLoading} />{status}<Button props={{ label: props.props.labels.settings, size: "sm", disabled }} on={{ press: props.on?.openSettings }} />{recovery ? <Button props={{ label: props.props.labels.retry, variant: "primary" }} on={{ press: props.on?.retry }} /> : <><Button props={{ label: props.props.labels.evaluate, variant: "primary", isPending: props.state === "submitting", disabled: disabled || repositoryInvalid || (props.props.repositoryDraft ?? props.props.repositoryUrl ?? "").trim() === "" }} on={{ press: props.on?.submit }} isLoading={isLoading} /><Button props={{ label: props.props.labels.feedback, disabled }} on={{ press: props.on?.openFeedback }} /></>}</SurfaceCard>
    return <><Link props={{ label: props.props.labels.back, icon: "back", emphasis: "muted" }} on={{ press: props.on?.back }} /><Heading props={{ content: props.props.title, level: 1 }} isLoading={isLoading} /><Text props={{ content: props.props.description }} isLoading={isLoading} />{props.props.difficulty === undefined ? null : <Badge props={{ content: props.props.difficulty }} isLoading={isLoading} />}<main>{briefContent}{submission}</main>{props.settingsOverlay === undefined || props.settingsOverlayProps === undefined ? null : <props.settingsOverlay {...props.settingsOverlayProps} />}</>
}
