"use client"

import Link from "next/link"
import { useState } from "react"

const LABS = [{ slug: "docker", title: "Docker playground", description: "Build and run a container with a guided workspace.", steps: 8 }, { slug: "kubernetes", title: "Kubernetes playground", description: "Deploy a service and inspect it one step at a time.", steps: 10 }, { slug: "rag", title: "RAG playground", description: "Pair your local agent and ask questions over your own sources.", steps: 12 }]
const lab = (slug: string) => LABS.find((item) => item.slug === slug)

export const PlaygroundHub = ({ displayId, isVi }: { displayId: string, isVi: boolean }) => <main className="mx-auto w-full max-w-4xl space-y-8 px-4 py-8 sm:px-6"><header className="space-y-2"><h1 className="text-3xl font-semibold">{isVi ? "Playground" : "Playground"}</h1><p className="text-muted-foreground">{isVi ? "Thực hành trong môi trường có hướng dẫn." : "Practice in a guided, hands-on environment."}</p></header><div className="grid gap-3 sm:grid-cols-2">{LABS.map((item) => <Link key={item.slug} href={`/courses/${displayId}/learn/playground/${item.slug}`} className="rounded-xl border border-default bg-content1 p-5 transition hover:border-primary"><h2 className="font-medium">{item.title}</h2><p className="mt-2 text-sm text-muted-foreground">{item.description}</p><p className="mt-4 text-xs text-muted-foreground">{item.steps} {isVi ? "bước" : "guided steps"}</p></Link>)}</div></main>

export const PlaygroundPrepare = ({ displayId, slug, isVi }: { displayId: string, slug: string, isVi: boolean }) => { const item = lab(slug); return <main className="mx-auto w-full max-w-3xl space-y-8 px-4 py-8 sm:px-6"><Link href={`/courses/${displayId}/learn/playground`} className="text-sm text-primary">← {isVi ? "Tất cả playground" : "All playgrounds"}</Link>{item ? <><header className="space-y-2"><h1 className="text-3xl font-semibold">{item.title}</h1><p className="text-muted-foreground">{item.description}</p></header><section className="space-y-3 rounded-xl border border-default bg-content1 p-5"><h2 className="font-medium">{isVi ? "Chuẩn bị môi trường" : "Prepare your environment"}</h2>{["Install the CLI", "Pair your local agent", "Check readiness"].map((step, index) => <div key={step} className="flex items-center gap-3 rounded-lg bg-content2 p-3"><span className="grid size-7 place-items-center rounded-full bg-primary text-sm text-primary-foreground">{index + 1}</span><span className="text-sm">{step}</span></div>)}<Link href={`/courses/${displayId}/learn/playground/${slug}/session`} className="mt-3 inline-flex h-10 items-center rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground">{isVi ? "Vào workspace" : "Enter workspace"} →</Link></section></> : <p className="rounded-lg border border-dashed border-default p-6 text-muted-foreground">{isVi ? "Không tìm thấy playground." : "This playground could not be found."}</p>}</main> }

export const PlaygroundSession = ({ displayId, slug, isVi }: { displayId: string, slug: string, isVi: boolean }) => { const item = lab(slug); const [step, setStep] = useState(0); const [connected, setConnected] = useState(false); if (!item) return <main className="mx-auto max-w-3xl px-4 py-8"><p>{isVi ? "Không tìm thấy playground." : "This playground could not be found."}</p></main>; return <main className="mx-auto grid w-full max-w-5xl gap-4 px-4 py-6 sm:px-6 lg:grid-cols-[16rem_1fr]"><aside className="rounded-xl border border-default bg-content1 p-4"><Link href={`/courses/${displayId}/learn/playground/${slug}`} className="text-sm text-primary">← {isVi ? "Thiết lập" : "Setup"}</Link><h1 className="mt-5 font-semibold">{item.title}</h1><ol className="mt-4 space-y-2">{Array.from({ length: item.steps }, (_, index) => <li key={index} className={`rounded-md px-3 py-2 text-sm ${index === step ? "bg-content2 font-medium" : "text-muted-foreground"}`}>Step {index + 1}</li>)}</ol></aside><section className="min-h-[28rem] rounded-xl border border-default bg-content1 p-5"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-default pb-4"><div><p className="text-xs uppercase tracking-wide text-muted-foreground">{connected ? "Connected" : "Waiting for agent"}</p><h2 className="mt-1 text-xl font-semibold">{item.title}</h2></div><button type="button" onClick={() => setConnected((value) => !value)} className="rounded-lg border border-default px-3 py-2 text-sm">{connected ? "Disconnect" : "Pair agent"}</button></div><div className="mt-6 rounded-lg bg-[#101318] p-4 font-mono text-sm text-green-300"><p>$ starci playground {slug}</p><p className="mt-2 text-slate-400">{connected ? "Agent ready. Follow the step guide." : "Waiting for a local agent connection..."}</p></div><div className="mt-6 flex flex-wrap justify-between gap-3"><button type="button" disabled={step === 0} onClick={() => setStep((value) => value - 1)} className="rounded-lg border border-default px-4 py-2 text-sm disabled:opacity-40">← Previous</button><button type="button" onClick={() => setStep((value) => Math.min(item.steps - 1, value + 1))} className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground">{step === item.steps - 1 ? "Complete" : "Next step →"}</button></div></section></main> }
