import { SurfaceListCard } from "@/components/branches/SurfaceListCard"
import { EmptyNotice } from "@/components/composites/EmptyNotice"
import { EvidenceRow } from "@/components/composites/EvidenceRow"
import { Button } from "@/components/leaves/Button"
import { Heading } from "@/components/leaves/Heading"
import { Input } from "@/components/leaves/Input"
import { Text } from "@/components/leaves/Text"
import type { ProfileSolvedChallenge } from "@/modules/api/graphql/queries/types/profile-evidence"
import { profileChallengeManageClassName, profileChallengeManageControlsClassName, profileChallengeManageSearchClassName } from "./classNames"
/** Challenge submissions and management actions. */
export type ProfileChallengeManageProps = { readonly state: "pending" | "ready" | "error"; readonly courseTitle?: string; readonly rows: ReadonlyArray<ProfileSolvedChallenge>; readonly query: string; readonly filterLabel: string; readonly on: { readonly back: () => void; readonly search: (value: string) => void; readonly filter: () => void; readonly select: (id: string) => void; readonly retry?: () => void; readonly clearSearch?: () => void; readonly browseCourses?: () => void } }
/** Draw searchable passed submissions for one course. */
export const ProfileChallengeManageBase = (props: ProfileChallengeManageProps) => { const loading = props.state === "pending"; const rows = loading ? [] : props.rows; const emptyAction = props.state === "error" ? { label: "Try again", icon: "retry" as const, press: props.on.retry } : props.query ? { label: "Clear search", icon: "retry" as const, press: props.on.clearSearch } : { label: "Browse courses", icon: "course" as const, press: props.on.browseCourses }; return <div className={profileChallengeManageClassName}><Button props={{ label: "← Challenges", variant: "ghost", size: "sm" }} on={{ press: props.on.back }} /><Heading props={{ content: props.state === "error" ? "Submissions couldn't be loaded" : `${props.courseTitle ?? "Course"} submissions`, level: 2 }} isLoading={loading} /><Text props={{ content: "Search and filter passed work in this course.", size: "sm", tone: "muted" }} isLoading={loading} /><div className={profileChallengeManageControlsClassName}><div className={profileChallengeManageSearchClassName}><Input props={{ id: "challenge-submission-search", name: "challenge-submission-search", placeholder: "Search submissions", defaultValue: props.query }} on={{ change: props.on.search }} /></div><Button props={{ label: props.filterLabel, variant: "outline" }} on={{ press: props.on.filter }} /></div><SurfaceListCard props={{ label: "Passed submissions" }} isLoading={loading}>{loading ? Array.from({ length: 3 }, (_, index) => <EvidenceRow key={`resting-${index}`} props={{ title: "", subtitle: "", fact: "" }} isLoading />) : rows.length === 0 ? <EmptyNotice props={{ icon: props.state === "error" ? "retry" : "search", message: props.state === "error" ? "Submissions couldn't be loaded." : props.query ? "No submissions match this search." : "No passed submissions were found.", actionLabel: emptyAction.label, actionIcon: emptyAction.icon }} on={{ act: emptyAction.press }} /> : rows.map((submission) => <EvidenceRow key={submission.id} props={{ title: submission.title, subtitle: [submission.selectedLang, submission.difficulty, submission.passedAt].filter(Boolean).join(" · "), fact: submission.score == null ? undefined : String(submission.score), factTone: "success", isPressable: true }} on={{ press: () => props.on.select(submission.id) }} />)}</SurfaceListCard></div> }
