import { SurfaceListCard } from "@starci/grammar/common"
import { Input, Button } from "@starci/grammar/common"
import { Icon } from "@starci/grammar/common"
import { iconSourceFor } from "@/components/leaves/Icon"
import { EmptyNotice } from "@starci/grammar/common"
import { EvidenceRow } from "@/components/composites/EvidenceRow"
import { Heading } from "@starci/grammar/common"
import { Text } from "@starci/grammar/common"
import type { ProfileSolvedChallenge } from "@/modules/api/graphql/queries/types/profile-evidence"
import { profileChallengeManageClassName, profileChallengeManageControlsClassName, profileChallengeManageSearchClassName } from "./classNames"
/** Challenge submissions and management actions. */
export type ProfileChallengeManageProps = { readonly state: "pending" | "ready" | "error"; readonly courseTitle?: string; readonly rows: ReadonlyArray<ProfileSolvedChallenge>; readonly query: string; readonly filterLabel: string; readonly on: { readonly back: () => void; readonly search: (value: string) => void; readonly filter: () => void; readonly select: (id: string) => void; readonly retry?: () => void; readonly clearSearch?: () => void; readonly browseCourses?: () => void } }
/** Draw searchable passed submissions for one course. */
export const ProfileChallengeManageBase = (props: ProfileChallengeManageProps) => { const loading = props.state === "pending"; const rows = loading ? [] : props.rows; const emptyAction = props.state === "error" ? { label: "Try again", icon: "retry" as const, press: props.on.retry } : props.query ? { label: "Clear search", icon: "retry" as const, press: props.on.clearSearch } : { label: "Browse courses", icon: "course" as const, press: props.on.browseCourses }; return <div className={profileChallengeManageClassName}><Button variant="ghost" size="sm" onPress={props.on.back}>{"← Challenges"}</Button><Heading level={2} isSkeleton={loading}>{props.state === "error" ? "Submissions couldn't be loaded" : `${props.courseTitle ?? "Course"} submissions`}</Heading><Text size={"sm"} tone={"muted"} isSkeleton={loading}>{"Search and filter passed work in this course."}</Text><div className={profileChallengeManageControlsClassName}><div className={profileChallengeManageSearchClassName}><Input id="challenge-submission-search" name="challenge-submission-search" label="Search submissions" placeholder="Search submissions" value={props.query} variant="primary" isDisabled={loading} onValueChange={props.on.search} /></div><Button variant="outline" onPress={props.on.filter}>{props.filterLabel}</Button></div><SurfaceListCard label={"Passed submissions"} isLoading={loading}>{loading ? Array.from({ length: 3 }, (_, index) => <EvidenceRow key={`resting-${index}`} props={{ title: "", subtitle: "", fact: "" }} isLoading />) : rows.length === 0 ? <EmptyNotice message={props.state === "error" ? "Submissions couldn't be loaded." : props.query ? "No submissions match this search." : "No passed submissions were found."} actionLabel={emptyAction.label} iconSource={iconSourceFor(props.state === "error" ? "retry" : "search", "leading")} actionStartContent={<Icon source={iconSourceFor(emptyAction.icon, "chip")} usage="chip" />} onAction={({ act: emptyAction.press })?.act} /> : rows.map((submission) => <EvidenceRow key={submission.id} props={{ title: submission.title, subtitle: [submission.selectedLang, submission.difficulty, submission.passedAt].filter(Boolean).join(" · "), fact: submission.score == null ? undefined : String(submission.score), factTone: "success", isPressable: true }} on={{ press: () => props.on.select(submission.id) }} />)}</SurfaceListCard></div> }
