import { SurfaceCard } from "@/components/branches/SurfaceCard"
import { EvidenceRow } from "@/components/composites/EvidenceRow"
import { Button } from "@/components/leaves/Button"
import { Heading } from "@/components/leaves/Heading"
import { Input } from "@/components/leaves/Input"
import { Text } from "@/components/leaves/Text"
import type { ProfileSolvedChallenge } from "@/modules/api/graphql/queries/types/profile-evidence"
/** Challenge submissions and management actions. */
export type ProfileChallengeManageProps = { readonly state: "pending" | "ready" | "error"; readonly courseTitle?: string; readonly rows: ReadonlyArray<ProfileSolvedChallenge>; readonly query: string; readonly filterLabel: string; readonly on: { readonly back: () => void; readonly search: (value: string) => void; readonly filter: () => void; readonly select: (id: string) => void } }
/** Draw searchable passed submissions for one course. */
export const ProfileChallengeManageBase = (props: ProfileChallengeManageProps) => { const loading = props.state === "pending"; const rows = loading ? [] : props.rows; return <div><Button props={{ label: "← Challenges", variant: "ghost", size: "sm" }} on={{ press: props.on.back }} /><Heading props={{ content: props.state === "error" ? "Submissions couldn't be loaded" : `${props.courseTitle ?? "Course"} submissions`, level: 2 }} isLoading={loading} /><Text props={{ content: "Search and filter passed work in this course.", size: "sm", tone: "muted" }} isLoading={loading} /><div><Input props={{ id: "challenge-submission-search", name: "challenge-submission-search", placeholder: "Search submissions", defaultValue: props.query }} on={{ change: props.on.search }} /><Button props={{ label: props.filterLabel, variant: "outline", size: "sm" }} on={{ press: props.on.filter }} /><Text props={{ content: `${props.rows.length} found`, size: "sm", tone: "muted" }} /></div><SurfaceCard props={{ label: `${props.rows.length} passed submissions` }}>{rows.length ? rows.map((submission) => <EvidenceRow key={submission.id} props={{ title: submission.title, subtitle: [submission.selectedLang, submission.difficulty, submission.passedAt].filter(Boolean).join(" · "), fact: submission.score == null ? undefined : String(submission.score), factTone: "success", isPressable: true }} on={{ press: () => props.on.select(submission.id) }} />) : <EvidenceRow props={{ title: props.state === "error" ? "Submissions couldn't be loaded." : props.query ? "No submissions match this search." : "No passed submissions were found." }} />}</SurfaceCard></div> }
