import { SurfaceCard } from "@starci/grammar/common"
import { SurfaceListCard } from "@starci/grammar/common"
import { Icon, iconSourceFor } from "@/components/leaves/Icon"
import { EmptyNotice } from "@starci/grammar/common"
import { EvidenceRow } from "@/components/composites/EvidenceRow"
import { Text } from "@starci/grammar/common"
import type { ProfileSolvedChallenge } from "@/modules/api/graphql/queries/types/profile-evidence"
import { profileEvidenceListClassName, profileEvidenceSurfaceClassName, profileMainClassName, profileProofMetricClassName, profileProofMetricsClassName } from "./classNames"
/** Public challenge standing and passed submissions. */
export type ProfileChallengesProps = { readonly strength: { readonly state: "pending" | "ready" | "error"; readonly data?: { readonly percentile?: number | null; readonly rank?: number | null; readonly xp?: number | null } | null }; readonly submissions: { readonly state: "pending" | "ready" | "error"; readonly data: ReadonlyArray<ProfileSolvedChallenge> }; readonly on: { readonly openCourse: (courseId: string) => void; readonly retry?: () => void; readonly browseCourses?: () => void } }
const formatDate = (value: string) => Number.isNaN(Date.parse(value)) ? value : new Intl.DateTimeFormat("en", { month: "short", day: "2-digit" }).format(new Date(value))
/** Draw challenge standing and passed submissions. */
export const ProfileChallengesBase = (props: ProfileChallengesProps) => {
    const metrics = [{ figure: String(props.submissions.data.length), label: "passed" }, ...(props.strength.data?.percentile == null ? [] : [{ figure: `Top ${props.strength.data.percentile}%`, label: "strength" }]), ...(props.strength.data?.rank == null ? [] : [{ figure: `#${props.strength.data.rank}`, label: "rank" }]), ...(props.strength.data?.xp == null ? [] : [{ figure: props.strength.data.xp.toLocaleString(), label: "XP" }])]
    const rows = props.submissions.state === "pending" ? [] : props.submissions.data
    return <div className={profileMainClassName}>
        <SurfaceCard label={"Challenge strength"} composition="joined"><div className={profileProofMetricsClassName}>{props.strength.state === "error" ? <div className={profileProofMetricClassName}><Text weight={"semibold"}>{"—"}</Text><Text size={"xs"} tone={"muted"}>{"Standing unavailable"}</Text></div> : metrics.map((metric) => <div className={profileProofMetricClassName} key={metric.label}><Text weight={"semibold"} isSkeleton={props.strength.state === "pending"}>{metric.figure}</Text><Text size={"xs"} tone={"muted"}>{metric.label}</Text></div>)}</div></SurfaceCard>
        <div className={profileEvidenceSurfaceClassName}><SurfaceListCard label={"Passed submissions"} isLoading={props.submissions.state === "pending"}><div className={profileEvidenceListClassName}>{props.submissions.state === "pending" ? Array.from({ length: 3 }, (_, index) => <EvidenceRow key={`resting-${index}`} props={{ title: "", subtitle: "", fact: "" }} isLoading />) : rows.length === 0 ? <EmptyNotice message={props.submissions.state === "error" ? "Passed submissions couldn't be loaded." : "No challenges passed yet."} description={props.submissions.state === "error" ? "Try this section again later." : "Passed graded challenges appear here."} actionLabel={props.submissions.state === "error" ? "Try again" : "Browse courses"} iconSource={iconSourceFor(props.submissions.state === "error" ? "retry" : "complete", "leading")} actionStartContent={<Icon source={iconSourceFor(props.submissions.state === "error" ? "retry" : "course", "chip")} usage="chip" />} onAction={({ act: props.submissions.state === "error" ? props.on.retry : props.on.browseCourses })?.act} /> : rows.map((item) => <EvidenceRow key={item.id} props={{ title: item.title, subtitle: [item.courseTitle, item.selectedLang, item.passedAt ? formatDate(item.passedAt) : undefined].filter(Boolean).join(" · "), fact: item.score == null ? undefined : String(item.score), factTone: "success", isPressable: Boolean(item.courseGlobalId ?? item.courseSlug) }} on={{ press: () => props.on.openCourse(item.courseGlobalId ?? item.courseSlug ?? "") }} />)}</div></SurfaceListCard></div>
    </div>
}
