import { SurfaceCard } from "@/components/branches/SurfaceCard"
import { SurfaceListCard } from "@/components/branches/SurfaceListCard"
import { EmptyNotice } from "@/components/composites/EmptyNotice"
import { Button } from "@/components/leaves/Button"
import { Heading } from "@/components/leaves/Heading"
import { Input } from "@/components/leaves/Input"
import { NavLink } from "@/components/leaves/NavLink"
import { Text } from "@/components/leaves/Text"
/** Local evidence panel selected independently from the quiz route mode. */
export type FlashcardQuizView = "setup" | "history" | "stats"
/** Transport state for the quiz workspace. */
export type CourseFlashcardsQuizBlockState = "pending" | "ready" | "empty" | "failed"
/** One comparable quiz history or coverage row. */
export type FlashcardQuizEvidenceRow = { readonly id: string; readonly title: string; readonly description: string; readonly fact: string }
/** Pure quiz setup data and actions. */
export type CourseFlashcardsQuizProps = { readonly pageState: FlashcardQuizView; readonly blockState: CourseFlashcardsQuizBlockState; readonly props: { readonly title: string; readonly subtitle: string; readonly reviewLabel: string; readonly quizLabel: string; readonly setupLabel: string; readonly historyLabel: string; readonly statsLabel: string; readonly activeView: FlashcardQuizView; readonly evidenceTitle: string; readonly evidenceRows: ReadonlyArray<FlashcardQuizEvidenceRow>; readonly configurationTitle: string; readonly sessionNameLabel: string; readonly sessionNamePlaceholder: string; readonly sessionName: string; readonly scopeLabel: string; readonly allScopeLabel: string; readonly dueScopeLabel: string; readonly selectedScope: "all" | "due"; readonly modeLabel: string; readonly quickLabel: string; readonly deepLabel: string; readonly levelLabel: string; readonly allLevelsLabel: string; readonly juniorLabel: string; readonly middleLabel: string; readonly seniorLabel: string; readonly staffLabel: string; readonly startLabel: string; readonly resumeLabel: string; readonly retryLabel: string; readonly emptyText: string; readonly failedText: string; readonly selectedMode: "quick" | "deep"; readonly selectedLevel: string | null; readonly cardCount: number; readonly cardsLabel: string; readonly resumeSessionId?: string }; readonly on: { readonly openReview: () => void; readonly selectView: (view: FlashcardQuizView) => void; readonly selectMode: (mode: "quick" | "deep") => void; readonly changeSessionName: (value: string) => void; readonly selectScope: (scope: "all" | "due") => void; readonly selectLevel: (level: string | null) => void; readonly start: () => void; readonly resume: (sessionId: string) => void; readonly retry: () => void } }
/** Compatibility export for existing imports. */

/** Draw guided setup, evidence views and resume path without fetching. */
export const CourseFlashcardsQuizBlockView = (props: CourseFlashcardsQuizProps) => {
    const data = props.props
    const loading = props.blockState === "pending"
    const levels = [[null, data.allLevelsLabel], ["junior", data.juniorLabel], ["middle", data.middleLabel], ["senior", data.seniorLabel], ["staff", data.staffLabel]] as const
    if (props.blockState === "failed" || props.blockState === "empty") return <EmptyNotice props={{ message: props.blockState === "failed" ? data.failedText : data.emptyText, actionLabel: props.blockState === "failed" ? data.retryLabel : undefined }} on={{ act: props.on.retry }} />
    return <main aria-label={data.title}><header><Heading props={{ content: data.title, level: 1 }} /><Text props={{ content: data.subtitle, size: "sm", tone: "muted" }} /></header><nav aria-label={data.title}><NavLink props={{ label: data.reviewLabel, kind: "tab" }} on={{ press: props.on.openReview }} /><NavLink props={{ label: data.quizLabel, kind: "tab", isCurrent: true }} />{(["setup", "history", "stats"] as const).map((view) => <NavLink key={view} props={{ label: view === "setup" ? data.setupLabel : view === "history" ? data.historyLabel : data.statsLabel, kind: "tab", isCurrent: props.pageState === view }} on={{ press: () => props.on.selectView(view) }} />)}</nav>{props.pageState === "setup" ? <SurfaceCard props={{ label: data.configurationTitle }} isLoading={loading}><Text props={{ content: `${data.cardCount} ${data.cardsLabel}`, size: "sm", tone: "muted" }} /><Input props={{ id: "flashcard-quiz-session-name", name: "sessionName", kind: "text", placeholder: data.sessionNamePlaceholder, defaultValue: data.sessionName }} on={{ change: props.on.changeSessionName }} isLoading={loading} /><Text props={{ content: data.scopeLabel, size: "sm", weight: "semibold" }} />{(["all", "due"] as const).map((scope) => <Button key={scope} props={{ label: scope === "all" ? data.allScopeLabel : data.dueScopeLabel, size: "sm", variant: data.selectedScope === scope ? "primary" : "outline" }} on={{ press: () => props.on.selectScope(scope) }} />)}<Text props={{ content: data.modeLabel, size: "sm", weight: "semibold" }} />{(["quick", "deep"] as const).map((mode) => <Button key={mode} props={{ label: mode === "quick" ? data.quickLabel : data.deepLabel, size: "sm", variant: data.selectedMode === mode ? "primary" : "outline" }} on={{ press: () => props.on.selectMode(mode) }} />)}<Text props={{ content: data.levelLabel, size: "sm", weight: "semibold" }} />{levels.map(([id, label]) => <Button key={id ?? "all"} props={{ label, size: "sm", variant: data.selectedLevel === id ? "primary" : "outline" }} on={{ press: () => props.on.selectLevel(id) }} />)}{data.resumeSessionId === undefined ? null : <Button props={{ label: data.resumeLabel, variant: "outline" }} on={{ press: () => props.on.resume(data.resumeSessionId!) }} />}{<Button props={{ label: data.startLabel, variant: "primary" }} on={{ press: props.on.start }} isLoading={loading} />}</SurfaceCard> : <SurfaceListCard props={{ label: data.evidenceTitle }} isLoading={loading}><ul>{data.evidenceRows.map((row) => <li key={row.id}><Text props={{ content: row.title, size: "sm", weight: "medium" }} /><Text props={{ content: row.description, size: "sm", tone: "muted" }} /><Text props={{ content: row.fact, size: "xs", tone: "muted" }} /></li>)}</ul></SurfaceListCard>}</main>
}
