import { ModalBranch } from "@/components/branches/ModalBranch"
import { SurfaceCard } from "@/components/branches/SurfaceCard"
import { EmptyNotice } from "@/components/composites/EmptyNotice"
import { Button } from "@/components/leaves/Button"
import { CodeBlock } from "@/components/leaves/CodeBlock"
import { Heading } from "@/components/leaves/Heading"
import { Text } from "@/components/leaves/Text"
import { Textarea } from "@/components/leaves/Textarea"
/** Finite runtime situations shown by the interview room. */
export type CourseMockInterviewSessionState = "connecting" | "live" | "syncing" | "expired" | "failed"
/** Transient operation refining a connected room. */
export type CourseMockInterviewSessionOperation = "streaming" | "syncing" | "grading"
/** One persisted transcript turn. */
export type CourseMockInterviewVisibleTurn = { readonly id: string; readonly role: "interviewer" | "candidate"; readonly label: string; readonly content: string }
/** Resolved copy, progress and transcript consumed by the pure room. */
export type CourseMockInterviewSessionData = { readonly sessionState?: CourseMockInterviewSessionState; readonly operation?: CourseMockInterviewSessionOperation; readonly title: string; readonly journeyLabel?: string; readonly journeyStageLabel?: string; readonly promptTitle: string; readonly stateLabel: string; readonly counterLabel: string; readonly progressLabel: string; readonly progress: number; readonly remainingLabel?: string; readonly turns: ReadonlyArray<CourseMockInterviewVisibleTurn>; readonly turnsLabel: string; readonly turnsEmptyLabel: string; readonly streamingText?: string; readonly interviewerPendingLabel: string; readonly answerLabel: string; readonly answerPlaceholder: string; readonly answer: string; readonly submitLabel: string; readonly abortLabel: string; readonly leaveLabel: string; readonly finishLabel: string; readonly retryLabel: string; readonly workspaceLabel: string; readonly workspaceEmptyLabel: string; readonly workspaceCode?: string; readonly notice?: string; readonly syncStatusLabel: string; readonly revisionLabel: string; readonly finishConfirmationOpen: boolean; readonly finishConfirmationTitle: string; readonly finishConfirmationDescription: string; readonly abandonConfirmationOpen: boolean; readonly abandonConfirmationTitle: string; readonly abandonConfirmationDescription: string; readonly confirmLabel: string; readonly abandonLabel: string; readonly cancelLabel: string }
/** User intents emitted by the pure room. */
export type CourseMockInterviewSessionActions = { readonly answer?: (value: string) => void; readonly ask?: () => void; readonly abort?: () => void; readonly leave?: () => void; readonly finish?: () => void; readonly retry?: () => void; readonly dismissConfirmation?: () => void; readonly confirmFinish?: () => void; readonly confirmAbandon?: () => void }
/** Public boundary of the presentational interview room. */
export type CourseMockInterviewSessionBlockProps = { readonly state: CourseMockInterviewSessionState; readonly props: CourseMockInterviewSessionData; readonly on?: CourseMockInterviewSessionActions }
/** Draw the full-page interview desk with ordinary semantic JSX. */
export const CourseMockInterviewSessionBlockBase = (props: CourseMockInterviewSessionBlockProps) => {
    const data = props.props
    const state = data.sessionState ?? props.state
    if (state === "failed" || state === "expired") return <EmptyNotice props={{ message: data.notice ?? data.retryLabel, actionLabel: data.retryLabel }} on={{ act: props.on?.retry }} />
    const busy = state === "connecting" || state === "syncing" || data.operation !== undefined
    const turns = data.turns
    return <><main aria-label={data.title}><header><Heading props={{ content: data.title, level: 1 }} /><Text props={{ content: data.stateLabel, size: "sm", tone: "muted" }} /><Button props={{ label: data.leaveLabel, variant: "outline" }} on={{ press: props.on?.leave }} /></header><Text props={{ content: data.counterLabel, size: "sm" }} /><div aria-label={data.progressLabel}>{data.progress}%</div><section aria-label={data.promptTitle}><Heading props={{ content: data.promptTitle, level: 2 }} />{data.streamingText === undefined ? null : <Text props={{ content: data.streamingText, size: "sm" }} />}{data.workspaceCode === undefined ? <Text props={{ content: data.workspaceEmptyLabel, size: "sm", tone: "muted" }} /> : <CodeBlock props={{ code: data.workspaceCode, language: "text" }} />}<Textarea props={{ id: "interview-answer", name: "answer", label: data.answerLabel, placeholder: data.answerPlaceholder, defaultValue: data.answer, disabled: busy }} on={{ change: props.on?.answer }} /><Button props={{ label: data.submitLabel, variant: "primary", disabled: busy || data.answer.trim() === "" }} on={{ press: props.on?.ask }} />{data.operation === "streaming" ? <Button props={{ label: data.abortLabel, variant: "outline" }} on={{ press: props.on?.abort }} /> : null}</section><SurfaceCard props={{ label: data.turnsLabel }}><ul>{turns.length === 0 ? <Text props={{ content: data.turnsEmptyLabel, size: "sm", tone: "muted" }} /> : turns.map((turn) => <li key={turn.id}><Text props={{ content: turn.label, size: "sm", weight: "semibold" }} /><Text props={{ content: turn.content, size: "sm" }} /></li>)}</ul></SurfaceCard>{data.notice === undefined ? null : <Text props={{ content: data.notice, size: "sm", live: "polite" }} />}{state === "syncing" ? <Text props={{ content: data.syncStatusLabel, size: "sm", live: "polite" }} /> : null}<Button props={{ label: data.finishLabel, disabled: busy }} on={{ press: props.on?.finish }} /></main><ModalBranch isOpen={data.finishConfirmationOpen || data.abandonConfirmationOpen} onDismiss={props.on?.dismissConfirmation ?? (() => undefined)}><Heading props={{ content: data.finishConfirmationOpen ? data.finishConfirmationTitle : data.abandonConfirmationTitle, level: 2 }} /><Text props={{ content: data.finishConfirmationOpen ? data.finishConfirmationDescription : data.abandonConfirmationDescription }} /><Button props={{ label: data.cancelLabel, variant: "outline" }} on={{ press: props.on?.dismissConfirmation }} /><Button props={{ label: data.finishConfirmationOpen ? data.confirmLabel : data.abandonLabel, variant: "primary" }} on={{ press: data.finishConfirmationOpen ? props.on?.confirmFinish : props.on?.confirmAbandon }} /></ModalBranch></>
}
